name: Build Godot Project

on:
  push:
    branches:
      - main
      - build-*

env:
  GODOT_VERSION: '4.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: godot-setup
        run: |
          mkdir /opt/godot && cd /opt/godot
          wget -q "https://github.com/godotengine/godot/releases/download/${{ env.GODOT_VERSION }}-stable/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip" -O godot.zip
          unzip godot.zip && rm godot.zip
          mv Godot_v* /usr/local/bin/godot
          godot --version --headless 
          
          templates_dir="/home/runner/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.stable"
          templates_url="https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz"
          mkdir -p "${templates_dir}"
          wget -q ${templates_url} -O templates.tpz 
          unzip templates.tpz -d /opt/godot && rm templates.tpz
          mv /opt/godot/templates/* "${templates_dir}"
          ls -lah "${templates_dir}"

      - name: game-build
        run: |
          mkdir -p build/
          file /home/runner/.local/share/godot/export_templates/4.3.stable/linux_release.x86_64
          file /home/runner/.local/share/godot/export_templates/4.3.stable/linux_debug.x86_64
          godot --headless --export-release "Linux/X11" build/my_game.x86_64

      - name: export
        uses: actions/upload-artifact@v4
        with:
          name: linux-X11
          path: build/game.x86_64